# Generated by Django 4.1.4 on 2023-01-12 23:27

from django.db import migrations, models
import django.db.models.deletion
import todoapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('datedue', models.DateTimeField(default=todoapp.models.one_week_from_now)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.todolist')),
            ],
            options={
                'ordering': ['datedue'],
            },
        ),
    ]
